artist:
  name: Aaron Richard
  tagline: Songs with Meaning
  # seo_title:
  # seo_description:
  contact_twitter_username: ARichardMusic
  # contact_phone: 
  # contact_email: 

social:
  - name: Facebook
    url: https://www.facebook.com/ARichardMusic/
  - name: Instagram
    url: https://www.instagram.com/arichardmusic/
  - name: Twitter
    url: https://twitter.com/ARichardMusic
  - name: Youtube
    url: https://www.youtube.com/channel/UCXlZ95GNxtEWNOAKQJ_XvIw
  - name: Spotify
    url: https://open.spotify.com/artist/0UbIzwCBITNCVBP3PU0AQz?si=ywfnms3sTmS43zqfAQupHQ

site_language: en
